/* do not change this file, it is auto generated by storybook. */

import { start, updateView } from "@storybook/react-native";

import "@storybook/addon-essentials/register";
import "@storybook/addon-interactions/register";

const normalizedStories = [
  {
    titlePrefix: "",
    directory: "../../packages/react-cerberus-story/src",
    files: "**/*.@(mdx|stories.@(js|jsx|ts|tsx))",
    importPathMatcher:
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.(mdx|stories\.(js|jsx|ts|tsx)))$/,
    // @ts-ignore
    req: require.context(
      "../../../packages/react-cerberus-story/src",
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.(mdx|stories\.(js|jsx|ts|tsx)))$/
    ),
  },
];

declare global {
  var view: ReturnType<typeof start>;
  var STORIES: typeof normalizedStories;
}

const annotations = [
  require("./preview"),
  require("@storybook/react-native/dist/preview"),
];

global.STORIES = normalizedStories;

// @ts-ignore
module?.hot?.accept?.();

if (!global.view) {
  global.view = start({
    annotations,
    storyEntries: normalizedStories,
  });
} else {
  updateView(global.view, annotations, normalizedStories);
}

export const view = global.view;
